### ISSUE TITLE
Questions about the confidence of key points

### ISSUE THREAD

**Issue by z411500976** [jhb86253817/PIPNet#35]
Hi,I'm sorry, I still don't understand, 
the max_cls returned by function forward_pip is the confidence scores of predicted landmarks. 
why is the confidence of the occluded points higher than that of the unoccluded points?
For example, if the face is partially occluded, I want to know which key points are occluded，Or the occluded key points are not displayed.
Can it be achieved based on the confidence of key points?

**Comment by jhb86253817** [comment]
Hi, I think the scores in max_cls can reflect the confidence of occlusion in general. However, PIPNet may not be suitable for such task, compared to traditional heatmap models, because PIPNet is supposed to be more robust, thus less sensitive to occlusion. A suggestion is that you may try removing the occlusion as data augmentation to make it somehow sensitive to occlusion.

**Comment by z411500976** [comment]
thanks again for your reply
